### ISSUE TITLE
Map and Layout

### ISSUE THREAD

**Issue by JeromSar** [derpfacedirk/Goldiriath#11]
We had discussion before, but let's put it on paper:

The current idea is to divide the map into two regions for the two factions. This approach to map design has benefits but also brings along problems. There is another possibility: allowing players to play in the same map, and thus take on the same quests and interactions with the world.

**Problem**
Which map design do we use, and why? 

The pro's and cons for the current (divided) layout are as follows:

**Pros**
- Each faction is unique and thus players are encouraged to play with different characters on each faction
- Players will feel a better connection to a faction, thus enhancing PvP battles.
- Building styles and designs could be customized to each faction.

**Cons**
- The map is divided, therefore architects will have to create a lot more land, villages and quests. Additionally, some duplication will most likely come into play.
- Players will almost never be able to explore the entire world.
- The factions are harder to balance.
- It's harder if not impossible to play or team up with friends on the other faction.
- The community is essentially divided into two parts, this especially becomes a problem during the time we are a small community. Players on the forums will be speaking of one specific quest, while other players will have no idea what that quest is about. This influences the all-players are all-players-are-equal concept.
- There could be per-faction playing styles, or religions.

**Questions to think about**
- How do we assign factions to players? Will it be a choice, or is it a random selection?
  - If the faction is assigned by choice, how will we avoid one faction becoming more popular than the other.
- With a divided layout, how do we handle faction balancing?
  - Will quests and towns be copied over?
  - What about narration, NPC characters, roles, etc?
- If we decide to let players play in the same region, how will PvP be managed?
  - Will there be certain PvP area's, or will PvP be allowed everywhere, but discouraged due to guards interfering?
  - How do we handle player level differences? Is PvP in town area's only allowed if player's are equally powerful?
  - Is there a Wilderness, or a place where PvP _should_ take place?
- With a divided layout, how do we accomplish a sense of server unity?
- How do we stimulate a strong connection between players and their faction?
  - Per faction guilds?
  - Per faction unique quests, next to global quests?
    - High value target bounties?

**Comment by derpfacedirk** [comment]
I'm personaly a big fan of the faction system
it will most defenetly be a choice
we cant really control it, but we can make a way that if one faction is oversaturated the pvp will have a max amount of players thus balancing it out
strong connections can be made using backstories
why is there a war, we need to think about what makes factions unique before we can answer that question
about cons:
it wont be harder to team up with friends in other factions it will be impossible
the community will be devided but the people who have no idea what something is about wont be reading those threads

**Comment by JeromSar** [comment]
After discussion in our staff meeting, we have agreed to go with the faction/divided layout.
