### ISSUE TITLE
Persistent Item Meta

### ISSUE THREAD

**Issue by JeromSar** [derpfacedirk/Goldiriath#12]
EDIT: After some review, we've decided persistent item meta through the use of a UUID in the lore is the best solution.

**TODO**
- [x] Implement persistent item meta https://github.com/Goldiriath/Goldiriath/commit/0f55fcdca4c5aed431fead626821154143ade062
- [x] Modify player item packet, fill it with the proper lore. https://github.com/Goldiriath/Goldiriath/commit/e463945926e23b4a22b9e1b1c7a07a3899df41f9

---

**Original Post**
After some review, the way we store item meta (tier, level, material, attributes, etc.) currently (through the use of it's 'lore' attribute) will become unbearably hard to manage. We need a better way to (persistently!) store data in itemstacks.

Itemstacks will eventually store data such as:
- Custom weight, if present
- Tier (for weapons)
- Level (for weapons)
- Attributes (beta)
- Custom name
- Custom lore (see comment 2 below).

Bukkit includes a Metadata API, but it unfortunately not persistent and thus it seems storing data in the form of NBT tags is our best option.

Helpful links:
- https://bukkit.org/threads/tutorial-attaching-metadata-to-itemstacks.221480/
- http://bukkit.org/threads/library-edit-or-create-nbt-tags-with-a-compact-class-no-obc-nms.178464/

**Comment by JeromSar** [comment]
After some review, I realized that here is another option. Using a serial number in the lore property of items. This way, messing with NBT will not be necessary. The item meta would be handled completely by the Goldiriath plugin, avoiding that any data gets lost by a change in Minecraft's NBT system.

This however, does pose one problem, the lore for each item will have to be a unique serial number. To fix this, I think that we might be able to hook into [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/), to modify the item packet before it gets sent to the player. That way, we can modify the lore property right before, and populate it with our custom persistent metadata. It's a hacky solution, but it should work.

What are your thoughts @derpfacedirk, @Hakhaktak and @cashenkes?

Helpful link: http://paste.ubuntu.com/7834502/

**Comment by cashenkes** [comment]
The second option, where you store the item data in the lore, seems to be the better option. And I do not think that it would be a huge problem if all the items would have a unique number in their lore, at least not in alpha.

**Comment by Hakhaktak** [comment]
I'm just wondering how I will be able to implement this in the texturepack... :p If you can give me some more information on how minecraft calls actual textures for such items I would be very grateful

**Comment by JeromSar** [comment]
@Hakhaktak Most of this data will not be available to the client, it serves only as data to handle certain gameplay mechanics (walk speed, weapon damage, display names, etc). The only data that will be available to the client is the item ID and it's metadata.

**Comment by Hakhaktak** [comment]
Copy that!
