### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by Hakhaktak** [derpfacedirk/Goldiriath#24]
I'm currently working on the "About us" for the website. I hope you like this idea for the layout (it's meant to look professional)

![about us](https://cloud.githubusercontent.com/assets/5718204/9514016/6779e13c-4c96-11e5-8396-5eb7f7015bb4.jpg)

**Comment by derpfacedirk** [comment]
@Hakhaktak we have a sepperate repository for the website please post this there

**Comment by Hakhaktak** [comment]
Im sorry wasnt aware of that

**Comment by JeromSar** [comment]
Now https://github.com/Goldiriath/Website/issues/1
