### ISSUE TITLE
Health system. Broken legs 'n stuff

### ISSUE THREAD

**Issue by Hakhaktak** [derpfacedirk/Goldiriath#27]
As already spoiled in another topic, I was working on an idea for a health system. 

A system that I think is a bit overkill, is the system MineZ uses. That said, there are some features I would like to copy. I was thinking of a system were natural health regeneration isn't a big thing. Players can regenerate by time, but I think it should cost a lot more time than the default regeneration. 

In order to regenerate your health quickly you'll have to either find a medic (=player) or a hospital(tent) with NPC's that will fix you up. I don't know if we should charge people for going to the hospital, are we going Canada healthcare or US healthcare? 

The medic's in this game will play a much larger role than the friendlies in MineZ. Only a medic (someone with medic passive skills, trained by the medic guild (or something)) can heal people. He can give medicine, he can stop bleeding (yeah I want bleeding, it's awesome) and he can even help wounded people.

As you may have mentioned, I said that he can stop bleeding and help wounded people, and yes I see a difference. Whereas someone who is bleeding may still fight with maybe a small debuff, seriously wounded people will no longer be able to fight. They can no longer sprint and just walk to a medic (or hospital ofc).

Now, how is getting wounded making PvP more interesting, won't it just ruin it? Well, let's say this, although it's a bit unrealistic: Someone can not get wounded in combat but only by fall damage or other out of combat damages. This way people will not make stupid attempts and jump 10 feet down into a castle just for combat, because you get wounded and you will simply die. Ohw, a medic can't heal himself if he's wounded, he can if he is bleeding tho. 

I'm in a hurry now, so leave suggestions below!

**Comment by Breesboar** [comment]
I'm not sure if this is a good thing. We make the game to be fun, not to be realistic. And as said before: this is an mmo not a survival game.

I think we should keep the ideas, like a slower health regen and medical skills, but diseases and woundings will just be ennoying and interrupting for people when playing our game.

**Comment by derpfacedirk** [comment]
A temporary slow debuff for falling long distances might be a good idea. also "medics" are a must in any mmo. it's just that usually they are called healers. Healing wil probably be done in some sort of subtree of magic

**Comment by Hakhaktak** [comment]
I dont want healing to be a subtree of magic since I don't want aoe healing effects. I rather see someone healing a player like in MineZ.. In fact, I'm absolutely not a fan of magic, so behold for more anti magic :p

@Breesboar Jumping from 10 blocks into a castle and backstabbing everyone isn't a great thing to happen either

**Comment by derpfacedirk** [comment]
small aoe heals are necisary, also magic will have a support subtree. this will contain several buffs and also healing. it would not be well balanced if anyone could just heal everyone around them

@Hakhaktak their fault for standing with their backs to a hostile castle

**Comment by ZoltarV** [comment]
Agreed with @Hakhaktak

**Comment by derpfacedirk** [comment]
@ZoltarV could you and @Hakhaktak further explain why
also every weapon has 3 possible role's (please see #6 for more info) if magic isn't going to do healing what will it do?

**Comment by Hakhaktak** [comment]
I do not think healing should be a magic ability but rather a direct player interaction. It will prevent players from getting healed whilst in combat (although it's still possible, but way harder) and so they must think before they run into enemy's. It will make the RPG more intellectual and interesting. People really need tactics and not a high level mage. 

It will, again, also prevent people from doing Rambo stuff since they will be punished for doing so. It makes it more hardcore but imo also more balanced

**Comment by derpfacedirk** [comment]
Without in battle healing, what is the point of healing at all?
You could just go stand in a city, get some food(IRL) and regen your health.
Also please keep in mind that pvp is END GAME, so level is not an issue, gear and skill are more to the point.
Healing skills will of course have a mana cost and aoe skill will have a higher mana cost. But the skills have to be present.
Otherwise you won't need a healer and the holy trinity of roles is broken completely, destroying a long tested and working system for all combat including PVE and PVP.

**Comment by JeromSar** [comment]
luv
