### ISSUE TITLE
Weapon types

### ISSUE THREAD

**Issue by Hakhaktak** [derpfacedirk/Goldiriath#29]
since we are talking a lot about PvP I thought it may be a good idea to think about weapons too. I came up with this (probably uncomplete) list.

Normal melee:
- Sword
- Long Sword
- Mace
- Club

Heavy melee
- War hammer
- Battle axe
- Double hand sword

Close melee
- dagger

Ranged weapons
- bow
- throwing knife (MLG)

Note: this list is just a suggestion, I highly doubt all of these are possible and good for a RPG, but just to give a few ideas

**Comment by cashenkes** [comment]
Al of then are possible I gues, but I do not think we have enough textures to support them all if we wanted. And I do hope that all the weapons we chose work for a MMO. (the more important part of an MMORPG)

**Comment by ZoltarV** [comment]
Make normal combat Sword, Ace and Mace

**Comment by Hakhaktak** [comment]
Ace == Axe?

**Comment by ZoltarV** [comment]
AND I OBJECT AGAINST THROWING KNIVES (I hate throwing knives if you haven't noticed yet)

**Comment by ZoltarV** [comment]
Hak, yes...

**Comment by derpfacedirk** [comment]
So under the new system that includes magic we can devide the weapons into four main groups:
1. melee
2. bow
3 wand(magic)
4 stealth
these are the four groups that all weapons will be devided into and what will determine possible skills.
under these we can put separate swords and maces if we want. but i would say that advanced weapons are more of a beta feature

**Comment by Breesboar** [comment]
Hmmm. I think this system is pretty solid, but if someone comes up with something different that is just as good as this system, I would prefer that one, because the melee, bow, stealth, mage system is the basic not-so-original thing.
But as long this new (good) idea does not exist, we'll have to stick with this system.

**Comment by cashenkes** [comment]
We are not really using a basic system. We are using a completely class-free system. And that is quite uncommon.
I would not even know how you would order things different than this (if you have a wand as weapon).
