### ISSUE TITLE
A system without mages

### ISSUE THREAD

**Issue by Hakhaktak** [derpfacedirk/Goldiriath#32]
Well, here is the idea you all have been waiting for. Enjoy it and treat it with some respect please :D

Guide classes (free to roam in between these classes)

Tank
Ranged
Medic
Light

```
Tank
```

The tank is the most heavy and lethal build in a MMORPG. The whole idea of the tank is that he can carry the team whilst in combat by taking the most enemy’s away from his teammates due to his excellent armor and combat strength. He then is buffed by the weight of his equipment. He has a reduced speed (depending on the armor) and a reduced attack speed (speed reducement by both armor and weapon, those are cumulative). He in fact can carry medical equipment, but the weight of the medical equipment together with his armor will make his attack speed dramatically low. Also, since a medic has special skills he, the tank won’t have any space for combat skills which will result in lower damage output. 

```
Ranged
```

The ranged class is a combination between Light and more or less armorless. That’s because the ranged players will have two weapons to carry, or they will not be able to fight melee. The of course can choose for a dagger, but a dagger will act like a butter knife trying to cut through metal when challenged with armor. The player will only be able to stab someone, but has to come very close in order to do so. In stead, he can wear a light sword, but it’ll reduce his dexterity and manoeuvrability. The player may choose reduce his armor, since he is a ranged unit it, so he won’t be facing any close combat, or at least not as much as a melee player would. A chestplate will reduce the player’s attack strength because in theory he won’t be able to pull his bow as far as he normally could. Of course, he could by specialized armor with only slightly less defense but a almost equivalent damage output as when he would’ve worn no armor, but this will cost a lot of money. 

```
Medic
```

The medic is specialized in healing people. He’ll be wearing a med kit (as told, everyone could, but it has weight and will reduce performance dramatically) and a sword (bow could be possible but not recommended since you need to be close to the tanks aka close combat is inevitable). The medkit would act similar to a quiver for ranged players and will contain several medical equipement. Normally bandages and medicinal herbs. A medic simply right clicks with the medical herbs on the tank and then with the bandages and the tank is healed (how much he’ll be healed is not balanced yet). This will be the most basic heal and instead of mana this will cost the medic gold, or resources, since it will be easy to make bandages (out of wool) and herbs can be “mined”. Certain plants can give (with a chance ratio of course) medicinal herbs.     The Medic do can upgrade his equipment by buying antibiotics or stronger medicinal herbs (rare plants, or only be bought in shops). Where the stronger medicinal herbs will not add an extra step to the process, antibiotics will, and it’ll made antibiotics underpowered. To balance this out we can either choose to make antibiotics cheaper, or reward the longer process with an even higher result. I think they should be cheaper than stronger herbs. In the end, both actions will heal the certain player a lot more than normal herbs with bandages would do. Note, antibiotics → herbs → bandages.
    So why what does the med kit do then? The medkit is a tool in which you can set up a configuration. It will look like the normal inventory (3 rows and 9 columns) except that the uppermost row will only have 3 columns (or more, depending on how many medical steps can be made). In these columns you put the medicinal equipment in the order you want to (again, (antibiotics → )herbs → bandages) and when right clicking with the medkit on a player it will automatically do these steps for you. It’ll dramatically slow down the healing time (in fact, it will kinda work like a spell now) and will take up so much less inventory space (since all the medical equipment is in the medkit’s inventory) that the medic can have more skills in his hotbar or other stuff if he wanted to. But, of course the medkit will have a weight (static or based on inventory of medkit?) and that will prevent players from making an OP medic.

```
Light
```

The Light (or scout) class is specialized in quick movement, fast attacks and hiding from opponents. It will have minimal armor and a light sword or mace (against armor). The most typical of playing as light is exploring rooms whilst sneaking at a good pace (yep, I’m thinking of special kinds of light armor that favor sneaking and the partial (50%) invisibility) and yet to be unseen by enemies. I think it’s quite a difficult class to play and a less extreme variant with more standard armor will be more favored by casual players. The light class will be very effective when sneaking through enemy city’s and may be favored with less fall damage.

Now, these classes are the most extreme and specialized situations, especially the Light class. Most players will find a combination between these and therefore we must ensure that there are no OP combinations (mayan sling f.e.) and we probably can’t do it without testing it. The weight system will be the key player in that system, making it impossible to fight with full armor and both a sword and a bow and a medkit to prevent these OP combinations. I fear that the most OP combination will be a lightish class with a medkit. Therefore, it may be an idea to prevent people to heal themselves with their own herbs, but that said, a team will need two medics. We may can come up with a skill that enables self healing, but can’t be combinated with certain other skills. For now, I want to leave it with this, but if you guys want me to make a more nuanced idea, tell me and I’ll do so!

**Comment by derpfacedirk** [comment]
@Hakhaktak first of a tank is not a lethal build in any way. he just soaks up damage and deals little
second your archer idea takes away from the freedom of the game. someones armour should have no direct impact on their damage output. just maybe attack speed. you want healing to cost something. this will not ever work. this will make healing unnecisary. also you would have to switch weapons to defend yourself? that will kill you seeing as healers are usually squisy as all hell. 

I think for reasons earlyer explained that this system will not work as well as a magic based system. also what weapon do healing skills come from. And finally even with the medkit the healing system will take far to much time. you have to be able to heal withing a split second and not have to worry if you have enough money or recources. this will underpower healing to the level where no individual will actually want to heal and so there will be no healers and  only tanks or maybe ranged

**Comment by Hakhaktak** [comment]
Im sorry about the tank but I thought it was meant to deal damage.

Archers with full armor? Nah I don't think you want an archer to be a ranged tank (for real a tank).

Did you even read what I said, herbs can be found in forests and bandages can be made from wool. 

Also, you have to click a skill. Now you have to click a medkit. I see no difference except for the medkit to be prepared.

I dont know what you meant with medics squishy as hell, but they do wear armor and are armed (with a sword mostly).

**Comment by JeromSar** [comment]
From my understanding, what is happening here, is that two parties have two different game philosophies. One is trying to create a fantasy RPG, while the other is trying to create a semi-realistic adventure RPG. I have to say, both approaches are both good game design patterns, but they conflict with each other.

Fantasy MMO RPGs are based around the concept that the three classes interact and support each other. In large scale battles, like you often see in these types of RPG's, each class is vital to the success of their clan/guild/faction.

Adventure MMO RPGs are more focused on the player's interaction with the NPC world, and one-on-one PvP and PvE battles. Each class just defines a certain layout that one player can have, and so, they aren't as dependent in combat as with fantasy MMO RPGs. And more often than not, these players will travel alone in the world, questing and exploring new terrain.

These two different approaches may both be excellent game design paradigms, but they are both very different from one another. And therefore, we must choose what design best fits our vision. At this stage, it's very complicated to implement elements from both designs.

**Comment by cashenkes** [comment]
@JeromSar I do agree that the 2 parties want to make a different game. Derp and I want to base goldiriath around a well tested and well received MMO system. @Hakhaktak is as far as I know making a complete new system. The point here is that I do not think your 2 types of game are correct, we are both trying to make an MMO. This means that we have a LOT of things similar.

Coming back to the main topic:
I do not think that this system you are describing here will work. A mayor mistake is trying to make the tank do damage, that will make a tank overpowered.
also If you are trying to make a non magic system, why have self heals? Why have a mana bar?

**Comment by Hakhaktak** [comment]
@cashenkes Again, I wasn't aware of the fact a tank should NOT do a high damage output, and I'm sorry for that. Further more, I do not understand your last questions, but I will still try to answer them.

I'm indeed thinking about self heals, quick bandage and stuff. Maybe you can say, for a medical bandage, you'll need scissors and for a quick bandage not. You indeed won't need a mana bar, it can be replaced with a stamina bar instead (or something else).

@JeromSar No this game is still MMO but only is the type of classes and some way of explaining the game changed. Instead of magic we'll have medics instead.

ps. @cashenkes spellcheck maybe? :D :p

**Comment by cashenkes** [comment]
@Hakhaktak in your first post you suggested a mana bar to be there, so that is why I asked the question of having a mana bar. 
Another question: What type's of armor will medics wear?

ps. don't refer to someone's spelling when you're not perfect yourself...

**Comment by Hakhaktak** [comment]
@cashenkes I guess everybody will wear the same type of armor, but you can create armor that's optimized for archery, sneaking, combat and medics (and other stuff if you want to). A medic could wear extreme armor in my opinion, but he will be slow and not as effective as when he would using optimized or lighter armor.

"This will be the most basic heal and instead of mana this will cost the medic gold"

I did not mentioned a mana bar but explained that instead of a spell costing mana, good herbs and antibiotics will cost money.

Btw people, this is not perfect, I know that, but it's an idea and I wonder if it's a thing you guys want to do instead of the standard MMORPG setting. Most important reason?

It makes us (more) unique.

Contra reason:

It may be not as good as the other system (has to be proven yet)

**Comment by cashenkes** [comment]
@Hakhaktak I guess its possible to make a system that is non magic. But I think that I would like a system with magic better. I just like the idea of elves and being able to shoot fireballs out of your wand. And as far as I can tell, a lot of other people (that play MMO's) do really like the magic system.

So I think its possible, but I do not think its better.

**Comment by derpfacedirk** [comment]
I agree with @cashenkes here.
also what would the mobs be that are inside dungeons?
seeing as undead aren't a possibility in your system

**Comment by Hakhaktak** [comment]
I see what you mean.

Well, you don't have to make everything realistic. But I just don't like a mage/magic system.. so yeah. But I see that it's probably not a good thing to do a different system, so we'll do a magic system, as planned.

**Comment by Hakhaktak** [comment]
But, why not both?
Or do you guys think it'll conflict with each other?

**Comment by derpfacedirk** [comment]
I think so yes.
Anyone have a problem with a system containing magic?

**Comment by cashenkes** [comment]
@Hakhaktak what do you mean with 'why not do both'? 

If im reading this correctly, yes a system with and without magic is kindof hard to make.

@derpfacedirk no problems here

**Comment by JeromSar** [comment]
It would be quite illogical to include both a medic system, and healing through the use of magic and/or skills. Because it the Healer/DPS/Tank layout has been battle tested by many other RPGs, I think it would be best to implement this for now. Of course, I think that healing at certain areas (in towns, for example), would not be a bad idea. This is, however, something to consider for late beta.

For now, I'm closing this issue. If you have any more remarks, just reply to this issue.
