### ISSUE TITLE
Damage calculation

### ISSUE THREAD

**Issue by cashenkes** [derpfacedirk/Goldiriath#38]
Last meeting we decided upon a few formula's that calculate damage for us. But we only decided on base damage. Wouldn't it be great to have multiple type's of weapons that did different kinds of damage. Right now everything does the same amount of damage, for example if you had a lv 1 staff (stick) it would hit exactly the same as a lv 1 bow, and I do not think that is correct.

So I think we need another set of multipliers to calculate the damage's of all the weapon types.

example multipliers:
- sword: 1
- bow: 1,2
- staff: 1,1
- knife: 0,8

**Comment by Breesboar** [comment]
Can't you use Damage/second instead of Damage/hit?

**Comment by cashenkes** [comment]
We could, but if we want to calculate something dammage on hit is more usefull. Dammage/sec could be calculated from dammage onhit and hits per sec, if we need that.

**Comment by Breesboar** [comment]
All right, I was just a little confused at first glance. The bow seemed to be overpowered, because of it's ability to ranged attacks ánd more attack damage, but I obviously forgot a sword hits a lot quicker than a bow.
