### ISSUE TITLE
Inventory lock

### ISSUE THREAD

**Issue by derpfacedirk** [derpfacedirk/Goldiriath#39]
Goldiriath will have an inventory slot system.
- [x] Prevent item use outside of item slots.
- [x] Retexture player hotbar

**Comment by cashenkes** [comment]
You might want to add: retexture glass panes to fit the closed of invetory slots. Other than that it seems good.

**Comment by JeromSar** [comment]
Completed by: https://github.com/Goldiriath/Goldiriath/commit/cb5bce3a0fd2b8a53007f847ef6c8802dcbef0bf and https://github.com/Goldiriath/Goldiriath/commit/f271f15faadf5eecb2b257d583fff60dcbb4a61d

Only retexturing remains.

**Comment by JeromSar** [comment]
Turns out we overthought this. You can simply retexture the hotbar background, making working with retextured glass panes completely unnecessary. The item-lock mechanism, is still a necessity.

**Comment by JeromSar** [comment]
Corrected in https://github.com/Goldiriath/Goldiriath/commit/3879d83540bf099df722d99e3f6404f20fcde431

**Comment by JeromSar** [comment]
End product: ![Hotbar](https://www.screenshottr.us/v/86f2a5b9792802a9f31a009b8252f37f/d2fe53c50b87d59d58393e58837a6ed5.png)
