### ISSUE TITLE
Aggro System

### ISSUE THREAD

**Issue by derpfacedirk** [derpfacedirk/Goldiriath#40]
Aggro system needs to be implemented.

See https://github.com/Goldiriath/Goldiriath/wiki/Aggro-Math
- [x] Aggro Math
  - [x] Math tests
- [x] Aggro implementation

**Comment by JeromSar** [comment]
Updated with @cashenkes @ver

**Comment by JeromSar** [comment]
Implemented in https://github.com/Goldiriath/Goldiriath/commit/4d303674db6f9269d26fcb6992ea6d378df8aab3
