### ISSUE TITLE
Shop System

### ISSUE THREAD

**Issue by JeromSar** [derpfacedirk/Goldiriath#41]
According to Dirk and Casper, a shop system will be necessary for alpha.

- [x] Shop definition (config)
- [x] Choose sell/buy dialog
- [x] Buy shop
  - [x] Transaction queue
  - [x] Safety checks (money, click location)
- [x] Sell shop

**Comment by cashenkes** [comment]
Would be really nice to have for alpha. If any further info is needed, send a message and I should be able to give some.

**Comment by Hakhaktak** [comment]
What kind of shops? I'm thinking of a blacksmith, market (with several types of food, weapons and stuff shops) but also specialized shops for both weapons and food. Health regenerating food, or Saturating Bread XTREME. Fletcher workshop, leather tanner. Armourer. That kind of shops.

**Comment by JeromSar** [comment]
@Hakhaktak The shop system will be customizable with configurations. However, a question to ask would be: are there any type of shops which do not function as buy/sell shops, but rather as more complicated interfaces?

**Comment by JeromSar** [comment]
Shows have now been implemented, hooray! \o/
