### ISSUE TITLE
Dialog and quest file loading order

### ISSUE THREAD

**Issue by derpfacedirk** [derpfacedirk/Goldiriath#62]
Due to the current loading order (quests first and dialogs after) quest that use a dialog handler for anything won't work. Just turning around the loading order will create similar problems

**Comment by JeromSar** [comment]
@derpfacedirk Pending bugfix is in https://github.com/Goldiriath/Goldiriath/commit/d2d3254aa3625cb687840fec610ab1063eda603a. No longer shows errors on startup.

Could you checkout and test this patch, and see if the error is resolved?

**Comment by derpfacedirk** [comment]
Issue appears to be fixed.
thank you

**Comment by JeromSar** [comment]
Still needs to be merged.
