### ISSUE TITLE
Script option "command" not working

### ISSUE THREAD

**Issue by derpfacedirk** [derpfacedirk/Goldiriath#65]
attempting to use this option gives an error message stating its not supported

**Comment by JeromSar** [comment]
Preliminary fix is at https://github.com/Goldiriath/Goldiriath/pull/67/commits/65adfa4e6145126def6b049dfcb105bd8ec33cc2. Could you try this out and see if the issue is resolved @derpfacedirk?

**Comment by derpfacedirk** [comment]
tried, error is gone.
issue apears fixed
