### ISSUE TITLE
Level calculation

### ISSUE THREAD

**Issue by derpfacedirk** [derpfacedirk/Goldiriath#7]
The leveling formula @JeromSar and I have developed is:

`f(x) = 50*(x-1)*x`
With `x` being the level and `f(x)` being the calculated XP necessary for that level.

`g(x) = 0.1*(sqrt(2*x+25)+5)`
With `x` being the XP and `g(x)` being the calculated level that can be acquired with that XP.

Max XP: `f(50) = 122500`.
##### Example

Player "Notch" is leveling from level 13 to level 14
Current XP: `f(13) = 7800`
Next level XP: `f(14) = 9100`
Required XP: `f(14) - f(13) = 9100 - 7800 = 1300`

Player "Jeb_" has `15800` XP.
Current level: `g(15800) = 17.2834` -> 17
Level XP: `15800 - f(17) = 500`
XP To next level: `f(18) - f(17) - 500 = 1300`

**Comment by JeromSar** [comment]
Implemented in https://github.com/Goldiriath/Goldiriath/commit/e650382a6a2ea6bfaf3529b6ae78ff3035eb410a
