### ISSUE TITLE
Chest/Loot tables

### ISSUE THREAD

**Issue by cashenkes** [derpfacedirk/Goldiriath#8]
We are sort of missing this small thing called loot.
- I would like a way to control what chests can drop, how long they take to respawn and the max  -  number of items they can spawn.
- Also, a way to make chestprofiles and 'chestspawn signs' would be appreciated.
- It would also be nice to be able to control mobdrops to.

---
- [x] Implement Loot Table loading/saving
- [x] Implement MobSpawn integration
- [x] Implement Chest loot tables

**Comment by JeromSar** [comment]
@cashenkes Alpha feature?

**Comment by cashenkes** [comment]
Yes of course

**Comment by derpfacedirk** [comment]
What I'm thinking right now is that we make 5 kinds of mob
trash
average
strong
dungeon boss
raid boss
each kind of mob has an amount of items it could drop
for each of these possible items there is a chance of dropping nothing, dropping an item the player can hardly use, dropping bad gear, normal gear, epic gear or legendary
the chances are different for each kind of mob but the same for 2 mobs of the same kind

**Comment by cashenkes** [comment]
looks good, but I have one question: Is the 'strong' mob a sort of mini boss?

**Comment by derpfacedirk** [comment]
pretty much, only they spawn in the open world
not a lot but they do

**Comment by cashenkes** [comment]
Are you going to make something simmilar to the _skull and crossbones_ zones in ESO?

**Comment by derpfacedirk** [comment]
i was thinking more like how LOTRO implemented it
that you can run into more powerful mobs in certain areas

**Comment by cashenkes** [comment]
Having some 'elite' zones is not a bad plan.

**Comment by JeromSar** [comment]
Casper and myself thought of some mobtiers that will per mob have different loot tables:
- Swarm
- Basic
- Elite
- Boss

These tiers won't actually be displayed above the mob's head. Instead, Casper thought it might be a good idea to instead color the mobs name depending on the tier.

**Comment by derpfacedirk** [comment]
I agree, later on in development we might want a few more but for now it is great

**Comment by Hakhaktak** [comment]
I agree

**Comment by cashenkes** [comment]
Example loottable

Zombie

(Elite) (0-1)
  Tier 2 armour -1-
  Tier 2 weapon -1-
  Golden apple -2-
  Tier 2 healing potion -4-
(Standard) (1-2)
  Tier 1 weapon -1-
  Tier 1 sword -1-
  Broken weapon -2-
  Broken armour -2-
  Food -4-
  Rotten flesh -5-
(Swarm) (0-2)
  Rotten flesh -6-
  Broken weapon -1-

Drop example:

1)A Swarm mob dies, 0-2 items wil now drop, the game has choosen for 1 item to drop. There is a 6-1 spawn ratio, out of 7 zombies 6 would drop a rotton flesh and 1 will drop a broken weapon

2)An Elite mob dies, 0-1 items from the Elite table can now drop, 1-2 items will drop from the Standard table and 0-2 items from the Swarm table wil be dropped.

Get the idea?

**Comment by Hakhaktak** [comment]
Sound interesting :3

**Comment by JeromSar** [comment]
Closed as per https://github.com/Goldiriath/Goldiriath/commit/4e8cf90a6ff959d0e63705e084bf90059d489d9c
